name: Badges

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 15 */3 *'

permissions:
  contents: write

jobs:
  badges:
    runs-on: ubuntu-latest
    steps:
      - name: Update badges
        run: npx update-my-badges ${{ github.repository_owner }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
